### ISSUE TITLE
Compatibility with ChartJS plugins

### ISSUE THREAD

**Issue by jhereu** [artifacthealth/phantom-chartjs#4]
Hi, is there any tested compatibility with `chartjs` plugins like `chartjs-plugin-datalabels`?

**Comment by meirgottlieb** [comment]
I haven't tried any plugins. Let me know how it goes.

**Comment by jhereu** [comment]
Sure, thanks. I close the issue then!

**Comment by jhereu** [comment]
Tried it and it's pretty simple. I already integrated `chart.piecelabel.js` at PR #5

**Comment by meirgottlieb** [comment]
Thanks for the PR. However, I don't want to make any plugins required. Can you figure out a way to make plugins optional like they are optional with ChartJS?
